[project]
name = "crewai-tutorial"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "crewai[google-genai,tools]>=1.9.3",
    "ipykernel>=7.1.0",
    "openrouter>=0.1.3",
]
